/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { IERC20 } from "./IERC20";
export type { POSC } from "./POSC";

export { Ownable__factory } from "./factories/Ownable__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { POSC__factory } from "./factories/POSC__factory";
